"use client";

import { useCallback, useEffect, useState } from "react";
import Image from "next/image";

/**
 * 2-slide rotating hero for the /join-as-rider page. Same shape and pacing as
 * the main page's `HeroAiBanners` — 21:9 ultra-wide, auto-advance, first
 * slide eager / priority for LCP, rest lazy. Pauses on `document.hidden`
 * and respects `prefers-reduced-motion`.
 *
 * Source images are generated by `scripts/generate-rider-banner.mjs` (Nano
 * Banana Pro via OpenRouter, compressed via sharp).
 */
const SLIDES = [
  {
    src: "/marketing/rider-hero-01.jpg",
    alt: "A Dawasarthi delivery rider standing beside their scooter in a Dibiyapur street at golden hour, holding a helmet, with a teal medical-cross delivery bag.",
  },
  {
    src: "/marketing/rider-hero-02.jpg",
    alt: "A Dawasarthi rider hands a medicine package to a smiling customer at her doorstep in Dibiyapur.",
  },
] as const;

const INTERVAL_MS = 7000;

export function RiderHeroBanners() {
  const [active, setActive] = useState(0);

  const go = useCallback((index: number) => {
    setActive((index + SLIDES.length) % SLIDES.length);
  }, []);

  useEffect(() => {
    const mq = window.matchMedia?.("(prefers-reduced-motion: reduce)");
    if (mq?.matches) return;

    let id: number | null = null;
    function start() {
      if (id != null) return;
      id = window.setInterval(() => {
        setActive((s) => (s + 1) % SLIDES.length);
      }, INTERVAL_MS);
    }
    function stop() {
      if (id != null) {
        window.clearInterval(id);
        id = null;
      }
    }
    function onVisibility() {
      if (document.hidden) stop();
      else start();
    }

    if (!document.hidden) start();
    document.addEventListener("visibilitychange", onVisibility);
    return () => {
      stop();
      document.removeEventListener("visibilitychange", onVisibility);
    };
  }, []);

  return (
    <section
      aria-roledescription="carousel"
      aria-label="Dawasarthi delivery rider moments"
      className="relative isolate w-full min-w-0 max-w-full overflow-x-clip bg-slate-100"
    >
      <div
        className={[
          "relative w-full min-w-0",
          // Phone: short banner strip (matches main page hero rhythm).
          "max-sm:h-[clamp(7.75rem,min(26svh,10.5rem),11.75rem)] max-sm:max-h-[200px]",
          // sm+: full-bleed cinematic 21:9 like the main hero (33/14 ≈ 21/9).
          "sm:h-auto sm:aspect-[33/14]",
        ].join(" ")}
      >
        {SLIDES.map((slide, index) => (
          <div
            key={slide.src}
            className={`absolute inset-0 transition-opacity duration-700 ease-out ${
              index === active
                ? "z-[1] opacity-100"
                : "z-0 pointer-events-none opacity-0"
            }`}
            aria-hidden={index !== active}
            role="group"
            aria-roledescription="slide"
            aria-label={`${index + 1} of ${SLIDES.length}`}
          >
            <Image
              src={slide.src}
              alt={slide.alt}
              fill
              priority={index === 0}
              loading={index === 0 ? "eager" : "lazy"}
              fetchPriority={index === 0 ? "high" : "auto"}
              quality={85}
              sizes="(max-width: 639px) 100vw, (max-width: 1279px) 100vw, 1200px"
              className="object-cover object-center"
            />
          </div>
        ))}

        {/* Subtle dot navigation, top-right so it doesn't fight the in-image CTAs */}
        <div className="absolute right-3 top-3 z-10 flex gap-1.5 rounded-full bg-slate-950/30 px-2 py-1.5 backdrop-blur sm:right-4 sm:top-4">
          {SLIDES.map((_, index) => (
            <button
              key={index}
              type="button"
              onClick={() => go(index)}
              aria-label={`Show slide ${index + 1} of ${SLIDES.length}`}
              aria-pressed={index === active}
              className={`h-2 rounded-full transition-all ${
                index === active
                  ? "w-5 bg-white"
                  : "w-2 bg-white/55 hover:bg-white/80"
              }`}
            />
          ))}
        </div>
      </div>
    </section>
  );
}
